"""Add music groups

Revision ID: 116764d6ebe6
Revises: 
Create Date: 2025-11-01 00:19:30.314630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116764d6ebe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_group_music', 'music_group_members', ['group_id', 'music_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_music', 'music_group_members', type_='unique')
    # ### end Alembic commands ###

